nn-students-2021h2/Food_Bot_Team_11

- Ershov_Alexey/Home_Work_3/HTTP_server.py
- Ershov_Alexey/Home_Work_3/cpu_operations.py
- Ershov_Alexey/Home_Work_3/request_client.py
- Ershov_Alexey/Home_Work_3/selector_server.py
- Ershov_Alexey/Home_Work_3/selectors_server.py
- Ershov_Alexey/Home_Work_3/simple_client.py
- Ershov_Alexey/Home_Work_3/socket_server.py
> Homework 3

- chat_bot_template.py
- human_class.py
- setup.py
> bot's skeleton

- chat_bot_template.py
1. added `start` func for new users and `hello` func for existing ones
2. added `buttons` handler
3. added skeletons for `acquaintance`, `update_user_data`, `nutrients_norm`, `add_meal`, `statistics` funcs
4. implemented `unknown` handler
> update `chat_bot_template` (see description)

- chat_bot_template.py
Reverts nn-students-2021h2/Food_Bot_Team_11#19
> Revert "update `chat_bot_template` (see description)"

- human_class.py
add `PROTEIN_IN_KCAL`, `CARB_IN_KCAL`, `FAT_IN_KCAL` constants for better readability
> add constants to `count_norm` method

- unittests.py
- unittests.py.bak
nothing informative, just trying to understand how github works
> created `unittests.py`

- unittests.py
- unittests.py.bak
Reverts nn-students-2021h2/Food_Bot_Team_11#26
> Revert "created `unittests.py`"

- chat_bot_template.py
- human_class.py
- setup.py
rework `buttons` function, all functions are called
minor fixes in `start` function
> rework `buttons` function

- chat_bot_template.py
- human_class.py
- setup.py
- user_database.py
**file `user_database.py` was created:**
- function `add_note` was added
- function `delete_note_with_id` was added
- function `update_user_name` was added
- function `update_user_age` was added
- function `update_user_height` was added
- function `update_user_weight` was added
- function `update_user_activity` was added
- function `update_user_goal` was added
- function `update_user_calorie_norm` was added
- function `update_user_protein_norm` was added
- function `update_user_fat_norm` was added
- function `update_user_carbohydrate_norm` was added
- function `get_user_object` was added
**implemented "acquaintance" with the user:**
- function `hello` was updated
- function `acquaintance` was updated
> user_database implementation

- user_meal_database.py
**file `user_meal_database.py` was created:**
function `add_meal_note` was added
function `delete_all_meal_notes` was added
function `delete_meal_note` was added
function `get_number_of_user_meals` was added
function `update_meal_dish` was added
function `update_meal_mass` was added
function `update_meal_date` was added
function `update_meal_time` was added
function `get_meal_object` was added
function `get_all_meals` was added
> `user_meal_database` implementation

- sourse/chat_bot_template.py
- sourse/human_class.py
- sourse/meal_class.py
- sourse/setup.py
- sourse/user_database.py
- sourse/user_meal_database.py
**Сhanges have been made to the following files:**
- chat_bot_template.py
- human_class.py
- meal_class.py
- setup.py
- user_database.py
- user_meal_database.py
close #38
> code refactoring with 'black'

- sourse/user_meal_database.py
added a function that generates unique id for one user
> adding function `generate_meal_id`

- sourse/foodbot.py
- sourse/handlers.py
- sourse/user_database.py
- sourse/utils.py
...and of course reformatted code with `black`
p.s. closes #41 and #31
> specified error types in `user_database.py`, added keyboard and first handler for existing users

- sourse/foodbot.py
- sourse/handlers.py
- sourse/meal_class.py
- sourse/user_class.py
- sourse/utils.py
- `handlers.py`
- `meal_class.py`
- `user_class.py`
- `utils.py`
closes #46
- added alternative entry points to the conversation
- added deleting an entry when meeting an already registered user
- fix data type in user_class constructor
> annotation update

- sourse/handlers.py
- sourse/user_class.py
New function `get_short_info` was added in `user_class.py`
> minnor user_class update

- sourse/handlers.py
- sourse/user_class.py
Reverts nn-students-2021h2/Food_Bot_Team_11#54
> Revert "minnor user_class update"

- sourse/handlers.py
- sourse/meal_class.py
- sourse/user_class.py
Function `get_short_info` was added in `user_class.py`
Function count_norm doesn't return anything anymore
> minnor fixes in user_class

- sourse/foodbot.py
- sourse/handlers.py
- sourse/user_class.py
- sourse/user_database.py
**The following functions have been added to the `handlers.py`:**
- `update_existing_user_data_continue`
- `update_exiting_user_name`
- `update_exiting_user_age`
- `update_exiting_user_sex`
- `update_exiting_user_height`
- `update_exiting_user_weight`
- `update_exiting_user_ability`
- `update_exiting_user_goal`
- `update_exiting_user_norm`
and added relevant MassegeHandlers
Function `update_user_sex` was added in `user_database.py`
Added the ability to undo parameter changes
> Update user info buttons

- sourse/foodbot.py
- sourse/handlers.py
- sourse/meal_class.py
- sourse/user_meal_database.py
**Added dialogue handlers in `handlers.py`:**
- add_new_meal
- get_meal_dish
- get_meal_size
- get_meal_calories
- get_meal_proteins
- get_meal_fats
- get_meal_carbohydrates
**`meal_class` was changed, added new attributes and functions in `meal_class.py`:**
- meal_to_database
- get_short_meal_info
- get_current_date
- get_current_time
- meal_from_dict
**added new functions in `user_meal_database.py`:**
- update_meal_average_calories
- update_meal_average_proteins
- update_meal_average_fats
- update_meal_average_carbohydrates
> Meal adding button

- sourse/foodbot.py
- sourse/handlers.py
- sourse/meal_class.py
- sourse/user_class.py
- sourse/user_meal_database.py
- sourse/utils.py
**Сorresponding handlers implemented:**
- get_statistic
- get_statistic_for_day
- get_statistic_for_week
- get_statistic_for_month
In `meal_class.py` was added functions:
- calculate_calories_for_day
- calculate_proteins_for_day
- calculate_fats_for_day
- calculate_carbohydrates_for_day
- calculate_calories_for_week
- calculate_proteins_for_week
- calculate_fats_for_week
- calculate_carbohydrates_for_week
- calculate_calories_for_month
- calculate_proteins_for_month
- calculate_fats_for_month
- calculate_carbohydrates_for_month
In `user_class.py` was added methods:
- get_meal_statistic_for_day
- get_meal_statistic_for_week
- get_meal_statistic_for_month
In `user_meal_database.py` was added functions:
- get_user_meal_for_day
- get_user_meal_for_week
- get_user_meal_for_month
close #35 …
> User statistic functional

- sourse/foodbot.py
- sourse/meal_class.py
- sourse/user_database.py
- sourse/utils.py
**In `user_database.py` was added functions:**
- get_all_user_info
**In `utils.py` was added functions:**
- send_every_day_info
close #70
> Sending daily statistics

- sourse/chat_bot_template.py
- sourse/foodbot.py
- sourse/handlers.py
- sourse/user_class.py
**Files were affected**
- `footbot.py`
- `handlers.py`
- `user_class.py`
close #75
> Сhange imports

- sourse/handlers.py
- sourse/learned_dish_database.py
- sourse/meal_class.py
- sourse/user_class.py
- sourse/user_database.py
- sourse/user_meal_database.py
- sourse/utils.py
**A description has been added for all methods and functions in the project**
close #60
> Function documentation

- sourse/learned_dish_database.py
- sourse/user_meal_database.py
**The exception blocks in `user_meal_database.py` and `learned_dish_database.py' have been fixed with pymysql exceptions.**
close #42
> Exception blocks fix

- sourse/handlers.py
- sourse/utils.py
1. removed `initial_keyboard`
2. changed `birth_date` key to `age` in user input summary
> bug fixes (see description)

- sourse/learned_dish_database.py
- sourse/user_database.py
- sourse/user_meal_database.py
**Database logs changed**
close #66
> Logs update

- README.md
but there is always room for improvement...
> finished `README.md`
